// src/app/layout.tsx

import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
 
import './globals.css';

  // Navbar.tsx
import Navbar from './components/Navbar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Agregamos el Navbar aquí */}
        <Navbar />
        
        {/* Contenido principal */}
        <main className="p-8">
          {children}
        </main>
      </body>
    </html>
  );
}
